# Generated by Django 5.1.4 on 2024-12-26 03:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="正常", max_length=3)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("remaining_battery", models.FloatField()),
            ],
            options={
                "db_table": "db_bicycle",
            },
        ),
        migrations.CreateModel(
            name="ParkingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_id", models.IntegerField()),
                ("area_name", models.CharField(max_length=20)),
                (
                    "parking_area",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "polygon_center",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "db_table": "db_parking_area",
            },
        ),
        migrations.CreateModel(
            name="staffUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_username", models.CharField(max_length=15, unique=True)),
                ("staff_password", models.CharField(max_length=15)),
                (
                    "staff_telephone",
                    models.CharField(max_length=12, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "db_staff_user",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=15)),
                ("telephone", models.CharField(max_length=12, null=True, unique=True)),
            ],
            options={
                "db_table": "db_user",
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_time", models.DateTimeField()),
                ("completion_time", models.DateTimeField()),
                (
                    "bicycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="enroll.bicycle"
                    ),
                ),
                (
                    "end_parking_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_area",
                        to="enroll.parkingarea",
                    ),
                ),
                (
                    "start_parking_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_area",
                        to="enroll.parkingarea",
                    ),
                ),
            ],
            options={
                "db_table": "db_dispatch",
            },
        ),
        migrations.AddField(
            model_name="bicycle",
            name="current_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enroll.parkingarea"
            ),
        ),
        migrations.CreateModel(
            name="DailyParkingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("vehicle_count", models.IntegerField()),
                (
                    "parking_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="enroll.parkingarea",
                    ),
                ),
            ],
            options={
                "db_table": "db_daily_parking_stats",
                "unique_together": {("date", "parking_area")},
            },
        ),
    ]
